[CmdletBinding()]
param(
    [switch]$Unregister,
    # Register an at-startup trigger instead of at-logon. Runs the service even
    # when nobody is signed in, but needs an elevated shell to register.
    [switch]$AtStartup,
    # Restart the running service. Needed after changing the password or the
    # server code, since config is read once at startup.
    [switch]$Restart
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($PSVersionTable.PSVersion.Major -lt 6) {
    Write-Warning 'Run this with pwsh (PowerShell 7). Windows PowerShell 5.1 reads this file as GBK and may mangle it.'
}

$taskName = 'Tab Out Remote Viewer'
$serverDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$launcherPath = Join-Path $serverDir 'start-hidden.vbs'

if ($Restart) {
    # Stop-ScheduledTask does not help here. The task launches the VBScript shim,
    # which fires node off with WScript.Shell.Run(..., 0, False) and exits — so the
    # node process is not a child the scheduler owns or can stop. It has to be
    # killed by port.
    #
    # That kill needs elevation: the node process was started by the scheduler, and
    # a normal shell gets "Access is denied" trying to stop it.
    $listener = Get-NetTCPConnection -LocalPort 8787 -State Listen -ErrorAction SilentlyContinue
    if ($listener) {
        try {
            Stop-Process -Id $listener[0].OwningProcess -Force -ErrorAction Stop
            Write-Host "Stopped running server (pid $($listener[0].OwningProcess))"
        }
        catch {
            throw "Could not stop the running server (pid $($listener[0].OwningProcess)): $($_.Exception.Message)`nRun this from an elevated shell."
        }
        Start-Sleep -Seconds 1
    }
    else {
        Write-Host 'Nothing listening on 8787; starting fresh.'
    }

    Start-ScheduledTask -TaskName $taskName
    Start-Sleep -Seconds 3
    $now = Get-NetTCPConnection -LocalPort 8787 -State Listen -ErrorAction SilentlyContinue
    if ($now) {
        Write-Host "Server is up (pid $($now[0].OwningProcess)) on $($now[0].LocalAddress):$($now[0].LocalPort)"
    }
    else {
        throw 'The task was started but nothing is listening on 8787. Check Task Scheduler history.'
    }
    return
}

if ($Unregister) {
    $existingTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($null -ne $existingTask) {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
        Write-Host "Unregistered scheduled task: $taskName"
    }
    else {
        Write-Host "No such scheduled task: $taskName"
    }
    if (Test-Path -LiteralPath $launcherPath) {
        Remove-Item -LiteralPath $launcherPath -Force
        Write-Host "Removed launcher: $launcherPath"
    }
    return
}

$serverScript = Join-Path $serverDir 'server.mjs'
$nodePath = (Get-Command node.exe -ErrorAction Stop).Source
$currentUser = [Security.Principal.WindowsIdentity]::GetCurrent().Name

if (-not (Test-Path -LiteralPath $serverScript -PathType Leaf)) {
    throw "Server entry point not found: $serverScript"
}

$isAdmin = (New-Object Security.Principal.WindowsPrincipal(
    [Security.Principal.WindowsIdentity]::GetCurrent()
)).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if ($AtStartup -and -not $isAdmin) {
    throw 'An at-startup trigger requires an elevated shell. Re-run as administrator, or drop -AtStartup to use the at-logon trigger.'
}

# Launch through a VBScript shim so no console window ever appears. Passing 0 as
# the second argument to WScript.Shell.Run hides the window outright; starting
# node.exe from the task directly would flash a console on every logon.
# Paths are baked in at install time so the shim does not depend on PATH, which
# is not guaranteed to include node in every session type.
$launcher = @"
' Generated by install-task.ps1 - do not edit by hand; re-run the installer instead.
' Starts the Tab Out remote viewer with no visible window.
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$serverDir"
shell.Run """$nodePath"" ""$serverScript""", 0, False
"@
Set-Content -LiteralPath $launcherPath -Value $launcher -Encoding ascii

$action = New-ScheduledTaskAction `
    -Execute 'wscript.exe' `
    -Argument ('"{0}"' -f $launcherPath) `
    -WorkingDirectory $serverDir

if ($AtStartup) {
    $trigger = New-ScheduledTaskTrigger -AtStartup
    # S4U runs without a stored password and without an interactive desktop.
    $principal = New-ScheduledTaskPrincipal -UserId $currentUser -LogonType S4U -RunLevel Limited
}
else {
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $currentUser
    $principal = New-ScheduledTaskPrincipal -UserId $currentUser -LogonType Interactive -RunLevel Limited
}

$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -MultipleInstances IgnoreNew `
    -DontStopIfGoingOnBatteries `
    -AllowStartIfOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
    -Hidden

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings `
    -Description 'Starts the local Tab Out remote viewer on 127.0.0.1:8787.' `
    -Force | Out-Null

Write-Host "Registered scheduled task: $taskName"
Write-Host "  Trigger:  $(if ($AtStartup) { 'at startup (runs without sign-in)' } else { 'at logon' })"
Write-Host "  Run as:   $currentUser"
Write-Host "  Launcher: $launcherPath"
Write-Host "  Server:   $serverScript"
Write-Host ''
Write-Host 'Start it now with:  Start-ScheduledTask -TaskName "Tab Out Remote Viewer"'
